-- Layer 2 of the desired state (see atlas.hcl). GENERATED - do not edit.
-- Regenerate with 'task migrate:schema' after any change to
-- internal/store/models. The Bun models are the source of truth; this file
-- only exists because the community Atlas build cannot run the loader.
--
-- Sorted, and with foreign keys lifted out of the CREATE TABLE statements, so
-- the output is byte-stable across runs. See the migrate:schema task.

CREATE TABLE "audit_event" ("id" uuid NOT NULL, "occurred_at" timestamptz NOT NULL DEFAULT now(), "actor" text NOT NULL, "actor_kind" actor_kind NOT NULL, "kind" audit_kind NOT NULL, "text" text NOT NULL, "source" text, PRIMARY KEY ("id"));
CREATE TABLE "capability" ("version_id" uuid NOT NULL, "source" capability_source NOT NULL, "name" text NOT NULL, "detail" jsonb, "level" capability_level NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("version_id", "source", "name"));
CREATE TABLE "category" ("id" uuid NOT NULL, "name" text NOT NULL, "slug" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), UNIQUE ("name"), UNIQUE ("slug"));
CREATE TABLE "component" ("version_id" uuid NOT NULL, "path" text NOT NULL, "kind" component_kind NOT NULL, "name" text NOT NULL, "note" text, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("version_id", "path"));
CREATE TABLE "device_authorization" ("id" uuid NOT NULL, "device_code_hash" bytea NOT NULL, "user_code" text NOT NULL, "requesting_host" text NOT NULL, "state" device_auth_state NOT NULL, "approved_by_identity_id" uuid, "expires_at" timestamptz NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), UNIQUE ("device_code_hash"), UNIQUE ("user_code"));
CREATE TABLE "fetch_attempt" ("id" uuid NOT NULL, "occurred_at" timestamptz NOT NULL DEFAULT now(), "source_kind" fetch_source_kind NOT NULL, "requested_ref" text NOT NULL, "outcome" fetch_outcome NOT NULL, "detail" text, PRIMARY KEY ("id"));
CREATE TABLE "finding" ("id" uuid NOT NULL, "scan_id" uuid NOT NULL, "version_id" uuid NOT NULL, "rule_id" text NOT NULL, "severity" finding_severity NOT NULL, "title" text NOT NULL, "detail" text, "evidence_path" text, "evidence_line" integer, "evidence_quote" text, "state" finding_state NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"));
CREATE TABLE "finding_evidence" ("id" uuid NOT NULL, "finding_id" uuid NOT NULL, "path" text NOT NULL, "line" integer, "quote" text, "role" evidence_role NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"));
CREATE TABLE "group_role_map" ("group_name" text NOT NULL, "role" org_role NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("group_name"));
CREATE TABLE "identity" ("id" uuid NOT NULL, "subject" text NOT NULL, "email" text, "display_name" text, "groups" text[] NOT NULL DEFAULT '{}', "last_seen_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), UNIQUE ("subject"));
CREATE TABLE "membership" ("profile_id" uuid NOT NULL, "subject_kind" subject_kind NOT NULL, "subject_ref" text NOT NULL, "role" membership_role NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("profile_id", "subject_kind", "subject_ref"));
CREATE TABLE "org_policy" ("id" integer NOT NULL, "scan_gate" scan_gate NOT NULL, "default_version_policy" version_policy NOT NULL, "require_signed_bundles" boolean NOT NULL, "community_needs_review" boolean NOT NULL, "rescan_on_new_version" boolean NOT NULL, "allow_personal_profiles" boolean NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"));
CREATE TABLE "outbox" ("id" uuid NOT NULL, "job_kind" text NOT NULL, "payload" jsonb NOT NULL, "idempotency_key" text NOT NULL, "state" outbox_state NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "delivered_at" timestamptz, PRIMARY KEY ("id"));
CREATE TABLE "override" ("finding_id" uuid NOT NULL, "reviewer_identity_id" uuid NOT NULL, "note" text, "expires_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("finding_id"));
CREATE TABLE "package" ("id" uuid NOT NULL, "publisher_id" uuid NOT NULL, "namespace" text NOT NULL, "name" text NOT NULL, "kind" package_kind NOT NULL, "category_id" uuid, "visibility" package_visibility NOT NULL, "parent_package_id" uuid, "latest_version_id" uuid, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "package_namespace_name" UNIQUE ("namespace", "name"));
CREATE TABLE "profile" ("id" uuid NOT NULL, "slug" text NOT NULL, "name" text NOT NULL, "description" text, "visibility" profile_visibility NOT NULL, "owner_team" text, "default_policy" version_policy NOT NULL, "forked_from_id" uuid, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), UNIQUE ("slug"));
CREATE TABLE "profile_entry" ("profile_id" uuid NOT NULL, "package_id" uuid NOT NULL, "mode" entry_mode NOT NULL, "pinned_version_id" uuid, "range_expr" text, "position" integer NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("profile_id", "package_id"));
CREATE TABLE "publisher" ("id" uuid NOT NULL, "slug" text NOT NULL, "display_name" text NOT NULL, "verified" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), UNIQUE ("slug"));
CREATE TABLE "revision" ("id" uuid NOT NULL, "profile_id" uuid NOT NULL, "seq" integer NOT NULL, "note" text, "lockfile" jsonb NOT NULL, "object_key" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "created_by" text NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "revision_profile_seq" UNIQUE ("profile_id", "seq"));
CREATE TABLE "scan" ("id" uuid NOT NULL, "version_id" uuid NOT NULL, "pack_version" text NOT NULL, "started_at" timestamptz NOT NULL DEFAULT now(), "finished_at" timestamptz, "verdict" verdict NOT NULL, "timed_out" boolean NOT NULL DEFAULT false, "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "scan_version_pack_version" UNIQUE ("version_id", "pack_version"));
CREATE TABLE "scan_check" ("scan_id" uuid NOT NULL, "check_id" text NOT NULL, "label" text NOT NULL, "result" check_result NOT NULL, "warn_count" integer NOT NULL DEFAULT 0, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("scan_id", "check_id"));
CREATE TABLE "session" ("id" uuid NOT NULL, "token_hash" bytea NOT NULL, "identity_id" uuid NOT NULL, "expires_at" timestamptz NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), UNIQUE ("token_hash"));
CREATE TABLE "signature" ("version_id" uuid NOT NULL, "ref" text, "kind" signature_kind NOT NULL, "verified_at" timestamptz, "verified_by" text, "result" signature_result, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("version_id"));
CREATE TABLE "sync_event" ("id" uuid NOT NULL, "identity_id" uuid NOT NULL, "profile_id" uuid NOT NULL, "revision_id" uuid NOT NULL, "host" text NOT NULL, "occurred_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"));
CREATE TABLE "sync_target" ("profile_id" uuid NOT NULL, "target" sync_target_kind NOT NULL, "enabled" boolean NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("profile_id", "target"));
CREATE TABLE "version" ("id" uuid NOT NULL, "package_id" uuid NOT NULL, "semver" text NOT NULL, "semver_sort" text NOT NULL, "object_key" text NOT NULL, "digest" bytea, "size_bytes" bigint, "manifest" jsonb NOT NULL, "tags" text[] NOT NULL DEFAULT '{}', "dist_tag" dist_tag NOT NULL, "verdict" verdict NOT NULL, "visible" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "version_package_semver" UNIQUE ("package_id", "semver"));
CREATE TABLE "version_tag" ("version_id" uuid NOT NULL, "tag" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("version_id", "tag"));
ALTER TABLE "device_authorization" ADD FOREIGN KEY ("approved_by_identity_id") REFERENCES "identity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "finding" ADD FOREIGN KEY ("scan_id") REFERENCES "scan" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "finding" ADD FOREIGN KEY ("version_id") REFERENCES "version" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "finding_evidence" ADD FOREIGN KEY ("finding_id") REFERENCES "finding" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "override" ADD FOREIGN KEY ("reviewer_identity_id") REFERENCES "identity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "package" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "package" ADD FOREIGN KEY ("parent_package_id") REFERENCES "package" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "package" ADD FOREIGN KEY ("publisher_id") REFERENCES "publisher" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "profile" ADD FOREIGN KEY ("forked_from_id") REFERENCES "profile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "profile_entry" ADD FOREIGN KEY ("pinned_version_id") REFERENCES "version" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "revision" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "scan" ADD FOREIGN KEY ("version_id") REFERENCES "version" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "session" ADD FOREIGN KEY ("identity_id") REFERENCES "identity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sync_event" ADD FOREIGN KEY ("identity_id") REFERENCES "identity" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sync_event" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sync_event" ADD FOREIGN KEY ("revision_id") REFERENCES "revision" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "version" ADD FOREIGN KEY ("package_id") REFERENCES "package" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
