package web

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"io/fs"
	"net/http"
	"path"
	"strings"

	"github.com/gin-gonic/gin"
)

// The whole static tree is embedded: a distroless image has no filesystem to
// read app.css, the fonts or datastar.js from, and nothing may be fetched from a
// CDN — the quickstart has to work offline.
//
//go:embed static
var staticFS embed.FS

var (
	staticRoot  fs.FS
	staticFiles http.Handler
	// assetVersions is a content hash per file, so /static can carry a
	// far-future immutable cache header without a stale app.css surviving a
	// deploy.
	assetVersions = map[string]string{}
)

func init() {
	sub, err := fs.Sub(staticFS, "static")
	if err != nil {
		panic("web: embedded static tree is missing: " + err.Error())
	}
	staticRoot = sub
	staticFiles = http.FileServer(http.FS(sub))

	err = fs.WalkDir(sub, ".", func(name string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil || entry.IsDir() {
			return walkErr
		}
		body, readErr := fs.ReadFile(sub, name)
		if readErr != nil {
			return readErr
		}
		sum := sha256.Sum256(body)
		assetVersions[name] = hex.EncodeToString(sum[:])[:12]
		return nil
	})
	if err != nil {
		panic("web: hashing embedded static tree: " + err.Error())
	}
}

// assetURL is the content-addressed URL of an embedded asset. A missing file
// yields the plain path rather than a panic: app.css is generated by
// `task gen:css`, and an unstyled page is a better failure than a process that
// will not start.
func assetURL(name string) string {
	if version, ok := assetVersions[name]; ok {
		return "/static/" + name + "?v=" + version
	}
	return "/static/" + name
}

func serveStatic(c *gin.Context) {
	name := strings.TrimPrefix(path.Clean("/"+c.Param("path")), "/")
	if name == "" || name == "." {
		c.Status(http.StatusNotFound)
		return
	}
	if _, err := fs.Stat(staticRoot, name); err != nil {
		c.Status(http.StatusNotFound)
		return
	}

	// Every asset is either immutable (a vendored font or script) or reached
	// through a content-hashed URL, so a year is safe and saves a conditional
	// request per asset per page.
	c.Header("Cache-Control", "public, max-age=31536000, immutable")
	c.Request.URL.Path = "/" + name
	staticFiles.ServeHTTP(c.Writer, c.Request)
}
