package pkgspec_test

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/santhosh-tekuri/jsonschema/v6"
	"github.com/stretchr/testify/require"

	"agent-manager/internal/domain/pkgspec"
)

// The manifest used throughout, conformant to Agent Plugins 1.0.0. It is written
// out rather than built from the Go struct on purpose: a fixture generated by the
// code under test cannot disagree with it.
const conformantPlugin = `{
  "$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json",
  "name": "platform-toolkit",
  "version": "1.3.0",
  "description": "Terraform and Kubernetes review helpers.",
  "author": {"name": "Platform", "email": "platform@example.dev"},
  "homepage": "https://example.dev/platform-toolkit",
  "repository": "https://github.com/example/platform-toolkit",
  "license": "Apache-2.0",
  "keywords": ["terraform", "kubernetes"],
  "extensions": {
    "dev.agent-manager": {
      "expectedCapabilities": [
        {"name": "network", "level": "allowlisted", "detail": ["registry.example.dev"]},
        {"name": "shell", "detail": ["terraform"]}
      ]
    }
  }
}`

func TestEmbeddedSchemasCompile(t *testing.T) {
	v, err := pkgspec.NewValidator()
	require.NoError(t, err)
	require.NotNil(t, v)

	ids := pkgspec.SchemaIDs()
	require.Len(t, ids, 5)
	require.Contains(t, ids, pkgspec.PluginSchema100)
	require.Contains(t, ids, pkgspec.PluginSchema110)
	require.Contains(t, ids, pkgspec.MCPSchema100)
	require.Contains(t, ids, pkgspec.MCPSchema110)
	require.Contains(t, ids, pkgspec.SkillFrontmatterSchema)
}

// The measurement the layer brief asked for, pinned so it cannot drift silently.
//
// santhosh-tekuri/jsonschema/v6 compiles `pattern` with Go's regexp package, so
// the published negative lookahead is a COMPILE error, not a validation quirk:
// the whole schema refuses to load and takes `additionalProperties: false` with
// it. This test proves both halves — that the raw pattern is rejected, and that
// the shipped validator loads anyway because the transform in embed.go lifted it.
func TestTheVendoredNameLookaheadCannotBeCompiledByRE2(t *testing.T) {
	const raw = `{
	  "$schema": "https://json-schema.org/draft/2020-12/schema",
	  "$id": "https://example.invalid/lookahead.json",
	  "type": "object",
	  "properties": {
	    "name": {"type": "string", "pattern": "^(?!.*(?:--|\\.\\.))[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$"}
	  }
	}`

	compiler := jsonschema.NewCompiler()
	doc, err := jsonschema.UnmarshalJSON(strings.NewReader(raw))
	require.NoError(t, err)
	require.NoError(t, compiler.AddResource("https://example.invalid/lookahead.json", doc))

	_, err = compiler.Compile("https://example.invalid/lookahead.json")
	require.Error(t, err, "if this ever compiles, the transform in embed.go is dead weight and should go")
	require.Contains(t, err.Error(), "invalid or unsupported Perl syntax: `(?!`")

	t.Run("the vendored file still carries the pattern the transform expects", func(t *testing.T) {
		vendored, err := pkgspec.RawSchema(pkgspec.PluginSchema100)
		require.NoError(t, err)
		require.Contains(t, string(vendored), `^(?!.*(?:--|\\.\\.))`,
			"the transform is keyed on this exact string and fails closed without it")
	})

	t.Run("the shipped validator loads and still enforces both halves", func(t *testing.T) {
		v, err := pkgspec.NewValidator()
		require.NoError(t, err)

		// The RE2 half.
		_, err = v.ValidatePluginManifest([]byte(`{"$schema":"` + pkgspec.PluginSchema100 + `","name":"-leading"}`))
		requireSchemaPath(t, err, "/properties/name/pattern")

		// The lookahead half, re-applied by CheckName and reported at the same path.
		_, err = v.ValidatePluginManifest([]byte(`{"$schema":"` + pkgspec.PluginSchema100 + `","name":"platform--toolkit"}`))
		requireSchemaPath(t, err, pkgspec.NameSchemaPath)
		require.Contains(t, err.Error(), "negative lookahead")
	})
}

func TestCheckNameAppliesTheWholePublishedRule(t *testing.T) {
	for _, tc := range []struct {
		name  string
		value string
		valid bool
	}{
		{name: "a plain name is accepted", value: "platform-toolkit", valid: true},
		{name: "dots and digits are accepted", value: "a1.b2-c3", valid: true},
		{name: "a single character is accepted", value: "a", valid: true},
		{name: "a doubled hyphen is refused by the lookahead half", value: "platform--toolkit"},
		{name: "a doubled dot is refused by the lookahead half", value: "platform..toolkit"},
		{name: "a leading hyphen is refused by the pattern", value: "-toolkit"},
		{name: "a trailing dot is refused by the pattern", value: "toolkit."},
		{name: "uppercase is refused by the pattern", value: "Platform"},
		{name: "an underscore is refused by the pattern", value: "platform_toolkit"},
		{name: "an empty name is refused", value: ""},
		{name: "65 bytes is refused by maxLength", value: strings.Repeat("a", 65)},
		{name: "64 bytes is accepted", value: strings.Repeat("a", 64), valid: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			require.Equal(t, tc.valid, pkgspec.ValidName(tc.value))
			if !tc.valid {
				require.NotEmpty(t, pkgspec.CheckName(tc.value))
				for _, problem := range pkgspec.CheckName(tc.value) {
					require.Equal(t, pkgspec.NameSchemaPath, problem.SchemaPath)
				}
			}
		})
	}
}

// R1's whole point: the design's manifest fields do not exist and the schema is
// closed. Each case here is a field the mockup shows.
func TestTheDesignsNonConformantManifestFieldsAreRejected(t *testing.T) {
	v, err := pkgspec.NewValidator()
	require.NoError(t, err)

	for _, tc := range []struct {
		name  string
		field string
		value string
	}{
		{name: "agentPluginsVersion", field: "agentPluginsVersion", value: `"1.0.0"`},
		{name: "publisher", field: "publisher", value: `"example"`},
		{name: "components", field: "components", value: `[{"kind":"skill"}]`},
		{name: "signature", field: "signature", value: `{"ref":"sigstore:x"}`},
		{name: "network", field: "network", value: `{"allow":["slack.com"]}`},
		{name: "filesystem", field: "filesystem", value: `{"write":["**"]}`},
		{name: "spec", field: "spec", value: `"openplugin/v1"`},
		{name: "providers", field: "providers", value: `["claude-code"]`},
		{name: "entry", field: "entry", value: `"SKILL.md"`},
	} {
		t.Run(tc.name+" is refused by additionalProperties", func(t *testing.T) {
			raw := withField(t, conformantPlugin, tc.field, tc.value)
			_, err := v.ValidatePluginManifest(raw)
			require.Error(t, err)
			require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
			requireSchemaPath(t, err, "/additionalProperties")
		})
	}
}

func TestAConformantManifestIsAccepted(t *testing.T) {
	v, err := pkgspec.NewValidator()
	require.NoError(t, err)

	plugin, err := v.ValidatePluginManifest([]byte(conformantPlugin))
	require.NoError(t, err)
	require.Equal(t, "platform-toolkit", plugin.Name)
	require.Equal(t, "1.3.0", plugin.Version)
	require.Equal(t, []string{"terraform", "kubernetes"}, plugin.Keywords)
	require.Equal(t, "platform@example.dev", plugin.Author.Email)
	require.Equal(t, []string{pkgspec.ExtensionNamespace}, plugin.Namespaces())
	require.JSONEq(t, conformantPlugin, string(plugin.Raw()),
		"the manifest is stored verbatim, not re-encoded")

	t.Run("only $schema and name are required", func(t *testing.T) {
		minimal := `{"$schema":"` + pkgspec.PluginSchema100 + `","name":"x"}`
		got, err := v.ValidatePluginManifest([]byte(minimal))
		require.NoError(t, err)
		require.Equal(t, "x", got.Name)
		require.Empty(t, got.Version)
	})

	t.Run("1.1.0 has the identical plugin field set", func(t *testing.T) {
		raw := strings.ReplaceAll(conformantPlugin, "/1.0.0/", "/1.1.0/")
		got, err := v.ValidatePluginManifest([]byte(raw))
		require.NoError(t, err)
		require.Equal(t, pkgspec.PluginSchema110, got.Schema)
	})
}

func TestAManifestMustNameASchemaThisBuildHolds(t *testing.T) {
	v, err := pkgspec.NewValidator()
	require.NoError(t, err)

	t.Run("a missing $schema is refused rather than defaulted", func(t *testing.T) {
		_, err := v.ValidatePluginManifest([]byte(`{"name":"x"}`))
		require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
		requireSchemaPath(t, err, "/required")
	})

	t.Run("an unknown version is refused rather than validated against a guess", func(t *testing.T) {
		raw := strings.ReplaceAll(conformantPlugin, "/1.0.0/", "/9.9.9/")
		_, err := v.ValidatePluginManifest([]byte(raw))
		require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
		requireSchemaPath(t, err, "/properties/$schema/const")
	})

	t.Run("an mcp $id is not accepted for a plugin manifest", func(t *testing.T) {
		raw := strings.ReplaceAll(conformantPlugin, "plugin.schema.json", "mcp.schema.json")
		_, err := v.ValidatePluginManifest([]byte(raw))
		require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
	})

	t.Run("garbage json is a manifest error, not a panic", func(t *testing.T) {
		_, err := v.ValidatePluginManifest([]byte(`{`))
		require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
	})
}

// FR-018a: the expected capability set has exactly one conformant home.
func TestTheExpectedCapabilitySetLivesOnlyUnderOurExtensionNamespace(t *testing.T) {
	v, err := pkgspec.NewValidator()
	require.NoError(t, err)

	plugin, err := v.ValidatePluginManifest([]byte(conformantPlugin))
	require.NoError(t, err)

	ext, present, err := plugin.AgentManager()
	require.NoError(t, err)
	require.True(t, present)
	require.Len(t, ext.ExpectedCapabilities, 2)
	require.Equal(t, "network", ext.ExpectedCapabilities[0].Name)
	require.Equal(t, "allowlisted", ext.ExpectedCapabilities[0].Level)

	t.Run("a shell capability is never recorded below review", func(t *testing.T) {
		require.Equal(t, "shell", ext.ExpectedCapabilities[1].Name)
		require.Equal(t, pkgspec.LevelReview, ext.ExpectedCapabilities[1].Level,
			"FR-018: a publisher's understatement must not become a reviewer's blind spot")
	})

	t.Run("an absent namespace is not an error, it is no expectation recorded", func(t *testing.T) {
		minimal := `{"$schema":"` + pkgspec.PluginSchema100 + `","name":"x"}`
		got, err := v.ValidatePluginManifest([]byte(minimal))
		require.NoError(t, err)
		_, present, err := got.AgentManager()
		require.NoError(t, err)
		require.False(t, present)
	})

	t.Run("a misspelled key inside our own namespace fails closed", func(t *testing.T) {
		raw := strings.ReplaceAll(conformantPlugin, "expectedCapabilities", "expectedCapabilties")
		got, err := v.ValidatePluginManifest([]byte(raw))
		require.NoError(t, err, "the published schema assigns no semantics inside a namespace")
		_, _, err = got.AgentManager()
		require.ErrorIs(t, err, pkgspec.ErrManifestInvalid,
			"a silently absent expected set suppresses the finding it should have raised")
	})

	t.Run("an unknown capability name is refused", func(t *testing.T) {
		raw := strings.ReplaceAll(conformantPlugin, `"name": "network"`, `"name": "nework"`)
		got, err := v.ValidatePluginManifest([]byte(raw))
		require.NoError(t, err)
		_, _, err = got.AgentManager()
		require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
	})

	t.Run("another vendor's namespace is left untouched", func(t *testing.T) {
		raw := withField(t, conformantPlugin, "extensions",
			`{"com.anthropic.claude-code":{"hooks":["pre-commit"]}}`)
		got, err := v.ValidatePluginManifest(raw)
		require.NoError(t, err)
		_, present, err := got.AgentManager()
		require.NoError(t, err)
		require.False(t, present)
		require.Equal(t, []string{"com.anthropic.claude-code"}, got.Namespaces())
	})
}

func TestMCPConfigIsIdenticalAcrossBothPublishedVersions(t *testing.T) {
	v, err := pkgspec.NewValidator()
	require.NoError(t, err)

	// PROVENANCE.md's measured correction to research.md R1: mcp.json did not
	// change between 1.0.0 and 1.1.0. Both files are compared byte for byte below,
	// modulo the two places the version legitimately appears.
	raw100, err := pkgspec.RawSchema(pkgspec.MCPSchema100)
	require.NoError(t, err)
	raw110, err := pkgspec.RawSchema(pkgspec.MCPSchema110)
	require.NoError(t, err)
	require.Equal(t,
		strings.ReplaceAll(strings.ReplaceAll(string(raw100), "/1.0.0/", "/VER/"), "Plugins 1.0.0", "Plugins VER"),
		strings.ReplaceAll(strings.ReplaceAll(string(raw110), "/1.1.0/", "/VER/"), "Plugins 1.1.0", "Plugins VER"),
		"if these ever differ, the version dispatch has a second job and research.md R1 was right after all")

	for _, id := range []string{pkgspec.MCPSchema100, pkgspec.MCPSchema110} {
		t.Run(id+" requires $schema and mcpServers", func(t *testing.T) {
			good := `{"$schema":"` + id + `","mcpServers":{"terraform-state":{"type":"stdio","command":"terraform-mcp"}}}`
			config, err := v.ValidateMCPConfig([]byte(good))
			require.NoError(t, err)
			require.Equal(t, []string{"terraform-state"}, config.ServerNames())

			_, err = v.ValidateMCPConfig([]byte(`{"$schema":"` + id + `"}`))
			require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
			requireSchemaPath(t, err, "/required")
		})
	}

	t.Run("PLUGIN_ROOT and PLUGIN_DATA cannot be overridden through env", func(t *testing.T) {
		raw := `{"$schema":"` + pkgspec.MCPSchema100 + `","mcpServers":{"x":{"type":"stdio","command":"c","env":{"PLUGIN_ROOT":"/tmp"}}}}`
		_, err := v.ValidateMCPConfig([]byte(raw))
		require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
	})
}

func TestSkillFrontmatterKeySetIsClosed(t *testing.T) {
	v, err := pkgspec.NewValidator()
	require.NoError(t, err)

	const good = "---\nname: terraform-plan-review\ndescription: Reviews a terraform plan for destructive changes.\nlicense: Apache-2.0\nallowed-tools:\n  - Read\n  - Grep\nmetadata:\n  owner: platform\ncompatibility:\n  claude-code: \">=1.0\"\n---\n\n# Terraform plan review\n"

	skill, err := v.ValidateSkillFrontmatter([]byte(good))
	require.NoError(t, err)
	require.Equal(t, "terraform-plan-review", skill.Name)
	require.Equal(t, []string{"Read", "Grep"}, skill.AllowedTools)
	require.Equal(t, []byte(good), skill.Raw())

	for _, tc := range []struct {
		name, body, schemaPath string
	}{
		{
			name:       "a key outside the set fails validation",
			body:       "---\nname: x\ndescription: y\nproviders:\n  - claude-code\n---\n",
			schemaPath: "/additionalProperties",
		},
		{
			name:       "the design's spec field fails validation",
			body:       "---\nname: x\ndescription: y\nspec: openplugin/v1\n---\n",
			schemaPath: "/additionalProperties",
		},
		{
			name:       "a missing description fails validation",
			body:       "---\nname: x\n---\n",
			schemaPath: "/required",
		},
		{
			name:       "a name with a doubled hyphen fails validation",
			body:       "---\nname: a--b\ndescription: y\n---\n",
			schemaPath: pkgspec.NameSchemaPath,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := v.ValidateSkillFrontmatter([]byte(tc.body))
			require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
			requireSchemaPath(t, err, tc.schemaPath)
		})
	}

	t.Run("no frontmatter at all is a manifest error", func(t *testing.T) {
		_, err := v.ValidateSkillFrontmatter([]byte("# Just a readme\n"))
		require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
	})

	t.Run("an unterminated fence is a manifest error", func(t *testing.T) {
		_, err := v.ValidateSkillFrontmatter([]byte("---\nname: x\ndescription: y\n"))
		require.ErrorIs(t, err, pkgspec.ErrManifestInvalid)
	})
}

func TestNormaliseSemver(t *testing.T) {
	for _, tc := range []struct {
		name, in, want string
	}{
		{name: "a plain semver is unchanged", in: "1.3.0", want: "1.3.0"},
		{name: "a v prefix is stripped", in: "v1.3.0", want: "1.3.0"},
		{name: "a tag ref is stripped", in: "refs/tags/v2.0.1", want: "2.0.1"},
		{name: "a partial version is completed", in: "1.3", want: "1.3.0"},
		{name: "a prerelease is preserved", in: "v1.0.0-rc.1", want: "1.0.0-rc.1"},
		{name: "build metadata is dropped", in: "1.0.0+build.7", want: "1.0.0"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := pkgspec.NormaliseSemver(tc.in)
			require.NoError(t, err)
			require.Equal(t, tc.want, got)
		})
	}

	for _, tc := range []struct{ name, in string }{
		{name: "an empty string is refused", in: ""},
		{name: "a branch name is refused", in: "main"},
		{name: "a date is refused", in: "2026-08-27"},
		{name: "a floating tag is refused", in: "latest"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := pkgspec.NormaliseSemver(tc.in)
			require.ErrorIs(t, err, pkgspec.ErrSemver)
		})
	}
}

// requireSchemaPath is the assertion US1 scenario 3 is about: the failure names
// the schema path that rejected it, not just "invalid".
func requireSchemaPath(t *testing.T, err error, want string) {
	t.Helper()
	require.Error(t, err)

	var manifestErr *pkgspec.ManifestError
	require.ErrorAs(t, err, &manifestErr)
	require.NotEmpty(t, manifestErr.Problems, "a manifest error with no problems names no schema path")

	paths := make([]string, 0, len(manifestErr.Problems))
	for _, problem := range manifestErr.Problems {
		paths = append(paths, problem.SchemaPath)
	}
	require.Containsf(t, paths, want, "schema paths were %v", paths)
}

// withField returns the manifest with one top-level field added or replaced.
func withField(t *testing.T, manifest, field, value string) []byte {
	t.Helper()

	var object map[string]json.RawMessage
	require.NoError(t, json.Unmarshal([]byte(manifest), &object))
	object[field] = json.RawMessage(value)

	out, err := json.Marshal(object)
	require.NoError(t, err)
	return out
}
