// Package hub provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package hub

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for DeviceTokenTokenType.
const (
	Bearer DeviceTokenTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the DeviceTokenTokenType enum.
func (e DeviceTokenTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for DeviceTokenErrorError.
const (
	AccessDenied         DeviceTokenErrorError = "access_denied"
	AuthorizationPending DeviceTokenErrorError = "authorization_pending"
	ExpiredToken         DeviceTokenErrorError = "expired_token"
	InvalidGrant         DeviceTokenErrorError = "invalid_grant"
	SlowDown             DeviceTokenErrorError = "slow_down"
)

// Valid indicates whether the value is a known member of the DeviceTokenErrorError enum.
func (e DeviceTokenErrorError) Valid() bool {
	switch e {
	case AccessDenied:
		return true
	case AuthorizationPending:
		return true
	case ExpiredToken:
		return true
	case InvalidGrant:
		return true
	case SlowDown:
		return true
	default:
		return false
	}
}

// Defines values for DeviceTokenRequestGrantType.
const (
	UrnIetfParamsOauthGrantTypeDeviceCode DeviceTokenRequestGrantType = "urn:ietf:params:oauth:grant-type:device_code"
)

// Valid indicates whether the value is a known member of the DeviceTokenRequestGrantType enum.
func (e DeviceTokenRequestGrantType) Valid() bool {
	switch e {
	case UrnIetfParamsOauthGrantTypeDeviceCode:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok          HealthStatus = "ok"
	Unavailable HealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for LockfileDefaultPolicy.
const (
	LockfileDefaultPolicyFloatingLatest LockfileDefaultPolicy = "floating-latest"
	LockfileDefaultPolicyPinned         LockfileDefaultPolicy = "pinned"
	LockfileDefaultPolicyRange          LockfileDefaultPolicy = "range"
)

// Valid indicates whether the value is a known member of the LockfileDefaultPolicy enum.
func (e LockfileDefaultPolicy) Valid() bool {
	switch e {
	case LockfileDefaultPolicyFloatingLatest:
		return true
	case LockfileDefaultPolicyPinned:
		return true
	case LockfileDefaultPolicyRange:
		return true
	default:
		return false
	}
}

// Defines values for LockfileGate.
const (
	Approval         LockfileGate = "approval"
	Block            LockfileGate = "block"
	WarnWithOverride LockfileGate = "warn-with-override"
)

// Valid indicates whether the value is a known member of the LockfileGate enum.
func (e LockfileGate) Valid() bool {
	switch e {
	case Approval:
		return true
	case Block:
		return true
	case WarnWithOverride:
		return true
	default:
		return false
	}
}

// Defines values for LockfileSchemaVersion.
const (
	N100 LockfileSchemaVersion = "1.0.0"
)

// Valid indicates whether the value is a known member of the LockfileSchemaVersion enum.
func (e LockfileSchemaVersion) Valid() bool {
	switch e {
	case N100:
		return true
	default:
		return false
	}
}

// Defines values for LockfileTargets.
const (
	LockfileTargetsClaudeCode LockfileTargets = "claude-code"
	LockfileTargetsCodex      LockfileTargets = "codex"
)

// Valid indicates whether the value is a known member of the LockfileTargets enum.
func (e LockfileTargets) Valid() bool {
	switch e {
	case LockfileTargetsClaudeCode:
		return true
	case LockfileTargetsCodex:
		return true
	default:
		return false
	}
}

// Defines values for LockfileEntryKind.
const (
	Plugin LockfileEntryKind = "plugin"
	Skill  LockfileEntryKind = "skill"
)

// Valid indicates whether the value is a known member of the LockfileEntryKind enum.
func (e LockfileEntryKind) Valid() bool {
	switch e {
	case Plugin:
		return true
	case Skill:
		return true
	default:
		return false
	}
}

// Defines values for LockfileEntryResolution.
const (
	LockfileEntryResolutionLatest LockfileEntryResolution = "latest"
	LockfileEntryResolutionPinned LockfileEntryResolution = "pinned"
	LockfileEntryResolutionRange  LockfileEntryResolution = "range"
)

// Valid indicates whether the value is a known member of the LockfileEntryResolution enum.
func (e LockfileEntryResolution) Valid() bool {
	switch e {
	case LockfileEntryResolutionLatest:
		return true
	case LockfileEntryResolutionPinned:
		return true
	case LockfileEntryResolutionRange:
		return true
	default:
		return false
	}
}

// Defines values for LockfileEntryVerdict.
const (
	Clean   LockfileEntryVerdict = "clean"
	Flagged LockfileEntryVerdict = "flagged"
)

// Valid indicates whether the value is a known member of the LockfileEntryVerdict enum.
func (e LockfileEntryVerdict) Valid() bool {
	switch e {
	case Clean:
		return true
	case Flagged:
		return true
	default:
		return false
	}
}

// Defines values for LockfileProfileVisibility.
const (
	LockfileProfileVisibilityOrganisation LockfileProfileVisibility = "organisation"
	LockfileProfileVisibilityPrivate      LockfileProfileVisibility = "private"
	LockfileProfileVisibilityShared       LockfileProfileVisibility = "shared"
)

// Valid indicates whether the value is a known member of the LockfileProfileVisibility enum.
func (e LockfileProfileVisibility) Valid() bool {
	switch e {
	case LockfileProfileVisibilityOrganisation:
		return true
	case LockfileProfileVisibilityPrivate:
		return true
	case LockfileProfileVisibilityShared:
		return true
	default:
		return false
	}
}

// Defines values for LockfileSkipReason.
const (
	FlaggedAwaitingApproval       LockfileSkipReason = "flagged-awaiting-approval"
	FlaggedBlockedByGate          LockfileSkipReason = "flagged-blocked-by-gate"
	NoCleanVersionAvailable       LockfileSkipReason = "no-clean-version-available"
	PinTargetMissing              LockfileSkipReason = "pin-target-missing"
	UnsignedAndSignaturesRequired LockfileSkipReason = "unsigned-and-signatures-required"
	VersionRejected               LockfileSkipReason = "version-rejected"
)

// Valid indicates whether the value is a known member of the LockfileSkipReason enum.
func (e LockfileSkipReason) Valid() bool {
	switch e {
	case FlaggedAwaitingApproval:
		return true
	case FlaggedBlockedByGate:
		return true
	case NoCleanVersionAvailable:
		return true
	case PinTargetMissing:
		return true
	case UnsignedAndSignaturesRequired:
		return true
	case VersionRejected:
		return true
	default:
		return false
	}
}

// Defines values for ProfileVisibility.
const (
	ProfileVisibilityOrganisation ProfileVisibility = "organisation"
	ProfileVisibilityPrivate      ProfileVisibility = "private"
	ProfileVisibilityShared       ProfileVisibility = "shared"
)

// Valid indicates whether the value is a known member of the ProfileVisibility enum.
func (e ProfileVisibility) Valid() bool {
	switch e {
	case ProfileVisibilityOrganisation:
		return true
	case ProfileVisibilityPrivate:
		return true
	case ProfileVisibilityShared:
		return true
	default:
		return false
	}
}

// Defines values for SyncReportTargets.
const (
	SyncReportTargetsClaudeCode SyncReportTargets = "claude-code"
	SyncReportTargetsCodex      SyncReportTargets = "codex"
)

// Valid indicates whether the value is a known member of the SyncReportTargets enum.
func (e SyncReportTargets) Valid() bool {
	switch e {
	case SyncReportTargetsClaudeCode:
		return true
	case SyncReportTargetsCodex:
		return true
	default:
		return false
	}
}

// DeviceAuthorization defines model for DeviceAuthorization.
type DeviceAuthorization struct {
	// DeviceCode Bearer credential. Stored hashed server-side; never logged.
	DeviceCode string `json:"device_code"`

	// ExpiresIn Seconds until the device code expires and polling must stop.
	//
	// Examples: 900
	ExpiresIn int64 `json:"expires_in"`

	// Interval Minimum seconds between polls of /v1/device/token.
	//
	// Examples: 5
	Interval int64 `json:"interval"`

	// UserCode Crockford base32, ambiguous glyphs excluded. Shape "HKQ2-9FTL".
	//
	// Examples: HKQ2-9FTL
	UserCode string `json:"user_code"`

	// VerificationUri The page the human opens to type the user code in.
	VerificationUri string `json:"verification_uri"`

	// VerificationUriComplete The same page with the code pre-filled, for a QR code or a click.
	VerificationUriComplete *string `json:"verification_uri_complete,omitempty"`
}

// DeviceAuthorizeRequest defines model for DeviceAuthorizeRequest.
type DeviceAuthorizeRequest struct {
	// ClientId The CLI's registered OAuth client identifier.
	//
	// Examples: agent-manager-cli
	ClientId string `json:"client_id"`

	// Host Hostname of the requesting machine. Bound to the authorisation and displayed to the approving human (FR-041), so approval is an informed act.
	//
	// Examples: dev-laptop-01
	Host string `json:"host"`

	// Scope Space-delimited scopes. Omitted means the client's default scope.
	//
	// Examples: profiles:read bundles:read
	Scope *string `json:"scope,omitempty"`
}

// DeviceToken defines model for DeviceToken.
type DeviceToken struct {
	// AccessToken Bearer token for every other operation here. Never logged.
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until the access token expires.
	//
	// Examples: 3600
	ExpiresIn int64 `json:"expires_in"`

	// RefreshToken Present only when the client may refresh without a second human approval.
	RefreshToken *string `json:"refresh_token,omitempty"`

	// TokenType Always Bearer.
	TokenType DeviceTokenTokenType `json:"token_type"`
}

// DeviceTokenTokenType Always Bearer.
type DeviceTokenTokenType string

// DeviceTokenError defines model for DeviceTokenError.
type DeviceTokenError struct {
	// Error authorization_pending means keep polling at the advertised interval; slow_down means back off and widen it. The rest are final - stop.
	//
	// Examples: authorization_pending
	Error *DeviceTokenErrorError `json:"error,omitempty"`
}

// DeviceTokenErrorError authorization_pending means keep polling at the advertised interval; slow_down means back off and widen it. The rest are final - stop.
//
// Examples: authorization_pending
type DeviceTokenErrorError string

// DeviceTokenRequest defines model for DeviceTokenRequest.
type DeviceTokenRequest struct {
	// ClientId Must be the same client_id that opened the authorisation.
	//
	// Examples: agent-manager-cli
	ClientId string `json:"client_id"`

	// DeviceCode The device_code handed back by /v1/device/authorize.
	DeviceCode string `json:"device_code"`

	// GrantType Fixed by RFC 8628 3.4. No other grant type is accepted here.
	GrantType DeviceTokenRequestGrantType `json:"grant_type"`
}

// DeviceTokenRequestGrantType Fixed by RFC 8628 3.4. No other grant type is accepted here.
type DeviceTokenRequestGrantType string

// Error defines model for Error.
type Error struct {
	// CorrelationId The request's correlation id, as also returned in the X-Correlation-ID header.
	CorrelationId *string `json:"correlation_id,omitempty"`

	// Detail Explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Per-field detail, when the failure was a validation failure.
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Status HTTP status code, repeated for client convenience.
	//
	// Examples: 404
	Status int64 `json:"status"`

	// Title Short, static summary of the problem type.
	//
	// Examples: Not Found
	Title string `json:"title"`

	// Type A URI reference to documentation for this error type.
	Type *string `json:"type,omitempty"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where it is wrong, e.g. body.targets[0] or path.revision.
	Location *string `json:"location,omitempty"`

	// Message What is wrong.
	Message string `json:"message"`

	// Value The offending value, echoed back.
	Value interface{} `json:"value,omitempty"`
}

// Health defines model for Health.
type Health struct {
	// Checks One entry per dependency this role needs.
	Checks []HealthCheck `json:"checks"`
	Status HealthStatus  `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	// Error Fixed text when the dependency is unreachable. The driver's message goes to the log, never to this unauthenticated body, because it can carry a host or a DSN.
	Error *string `json:"error,omitempty"`

	// Name Examples: database
	Name string `json:"name"`
	Ok   bool   `json:"ok"`
}

// Lockfile defines model for Lockfile.
type Lockfile struct {
	// DefaultPolicy Examples: pinned
	DefaultPolicy *LockfileDefaultPolicy `json:"defaultPolicy,omitempty"`

	// Entries Packages this revision resolves to an exact version.
	Entries []LockfileEntry `json:"entries"`

	// Gate The org scan gate in force at resolution. Recorded so a lockfile explains itself later.
	//
	// Examples: approval
	Gate LockfileGate `json:"gate"`

	// Note The publisher's note on this revision.
	//
	// Examples: Quarterly refresh
	Note *string `json:"note,omitempty"`

	// Profile Identifies the profile this revision belongs to.
	Profile    LockfileProfile `json:"profile"`
	ResolvedAt time.Time       `json:"resolvedAt"`

	// Revision Sequential per profile, no gaps.
	//
	// Examples: 7
	Revision      int64                 `json:"revision"`
	SchemaVersion LockfileSchemaVersion `json:"schemaVersion"`

	// Skipped FR-036: an excluded package is reported with its reason, never silently omitted.
	Skipped []LockfileSkip `json:"skipped"`

	// Targets Which agent directories the CLI should write. Advisory to the client; the server stores nothing per target (FR-039).
	Targets []LockfileTargets `json:"targets"`
}

// LockfileDefaultPolicy Examples: pinned
type LockfileDefaultPolicy string

// LockfileGate The org scan gate in force at resolution. Recorded so a lockfile explains itself later.
//
// Examples: approval
type LockfileGate string

// LockfileSchemaVersion defines model for Lockfile.SchemaVersion.
type LockfileSchemaVersion string

// LockfileTargets defines model for Lockfile.Targets.
type LockfileTargets string

// LockfileEntry defines model for LockfileEntry.
type LockfileEntry struct {
	Digest string `json:"digest"`

	// Id publisher/name
	//
	// Examples: acme/code-review
	Id string `json:"id"`

	// Kind Examples: skill
	Kind LockfileEntryKind `json:"kind"`

	// ObjectKey Examples: bundles/acme/code-review/2.4.1/bundle.tar.zst
	ObjectKey string `json:"objectKey"`

	// Override Present only when a flagged version resolved under warn-with-override.
	Override *LockfileOverride `json:"override,omitempty"`

	// Resolution Examples: pinned
	Resolution LockfileEntryResolution `json:"resolution"`

	// Signature Signature provenance, when the source carried one.
	Signature *LockfileSignature `json:"signature,omitempty"`

	// Verdict Examples: clean
	Verdict LockfileEntryVerdict `json:"verdict"`

	// Version Examples: 2.4.1
	Version string `json:"version"`
}

// LockfileEntryKind Examples: skill
type LockfileEntryKind string

// LockfileEntryResolution Examples: pinned
type LockfileEntryResolution string

// LockfileEntryVerdict Examples: clean
type LockfileEntryVerdict string

// LockfileOverride defines model for LockfileOverride.
type LockfileOverride struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Note Examples: Network call is to our own registry
	Note string `json:"note"`

	// Reviewer Examples: security-lead@example.dev
	Reviewer string `json:"reviewer"`
}

// LockfileProfile defines model for LockfileProfile.
type LockfileProfile struct {
	// Name Examples: Platform baseline
	Name string `json:"name"`

	// Slug Examples: platform-baseline
	Slug string `json:"slug"`

	// Visibility Examples: organisation
	Visibility *LockfileProfileVisibility `json:"visibility,omitempty"`
}

// LockfileProfileVisibility Examples: organisation
type LockfileProfileVisibility string

// LockfileSignature defines model for LockfileSignature.
type LockfileSignature struct {
	// Ref Examples: sigstore:acme/code-review@2.4.1
	Ref *string `json:"ref,omitempty"`

	// Verified False until Sigstore verification ships (FR-048a). Never render a false value as a pass.
	Verified *bool `json:"verified,omitempty"`
}

// LockfileSkip defines model for LockfileSkip.
type LockfileSkip struct {
	// Detail Examples: SH-NET-002 in postinstall.sh
	Detail *string `json:"detail,omitempty"`

	// Id Examples: acme/legacy-helper
	Id string `json:"id"`

	// Reason Examples: flagged-awaiting-approval
	Reason LockfileSkipReason `json:"reason"`

	// WouldHaveResolvedTo Examples: 1.9.0
	WouldHaveResolvedTo *string `json:"wouldHaveResolvedTo,omitempty"`
}

// LockfileSkipReason Examples: flagged-awaiting-approval
type LockfileSkipReason string

// Profile defines model for Profile.
type Profile struct {
	// HeadRevision The most recent published revision number.
	//
	// Examples: 7
	HeadRevision int64 `json:"headRevision"`

	// Name Human-readable name as shown in the web UI.
	//
	// Examples: Platform baseline
	Name string `json:"name"`

	// PackageCount Packages in the head revision, excluding skipped entries.
	//
	// Examples: 12
	PackageCount int64 `json:"packageCount"`

	// Slug URL-safe identifier, unique within the organisation.
	//
	// Examples: platform-baseline
	Slug string `json:"slug"`

	// Visibility How this profile came to be readable by this identity.
	//
	// Examples: organisation
	Visibility *ProfileVisibility `json:"visibility,omitempty"`
}

// ProfileVisibility How this profile came to be readable by this identity.
//
// Examples: organisation
type ProfileVisibility string

// ProfileList defines model for ProfileList.
type ProfileList struct {
	// Profiles Readable profiles. Order is not part of the contract.
	Profiles []Profile `json:"profiles"`
}

// SyncReport defines model for SyncReport.
type SyncReport struct {
	// Host Hostname the sync landed on, for the audit row.
	//
	// Examples: dev-laptop-01
	Host string `json:"host"`

	// Profile Slug of the profile that was synced.
	//
	// Examples: platform-baseline
	Profile string `json:"profile"`

	// Revision The exact revision the client resolved against.
	//
	// Examples: 7
	Revision int64 `json:"revision"`

	// Skipped Entry ids the client skipped locally, if any.
	Skipped *[]string `json:"skipped,omitempty"`

	// Targets Agent directories the client actually wrote.
	Targets []SyncReportTargets `json:"targets"`
}

// SyncReportTargets defines model for SyncReport.Targets.
type SyncReportTargets string

// DeviceAuthorizeJSONRequestBody defines body for DeviceAuthorize for application/json ContentType.
type DeviceAuthorizeJSONRequestBody = DeviceAuthorizeRequest

// DeviceTokenFormdataRequestBody defines body for DeviceToken for application/x-www-form-urlencoded ContentType.
type DeviceTokenFormdataRequestBody = DeviceTokenRequest

// ReportSyncJSONRequestBody defines body for ReportSync for application/json ContentType.
type ReportSyncJSONRequestBody = SyncReport

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetBundle Download an immutable version bundle
	//
	// Returns the `bundle.tar.zst` bytes, or a 307 to a pre-signed object-store URL. The `Digest` header carries the sha256 the client MUST verify before writing anything to disk. A rejected version is never served regardless of gate (FR-029).
	//
	// Corresponds with GET /v1/bundles/{publisher}/{name}/{version} (the `GetBundle` operationId).
	GetBundle(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeviceAuthorizeWithBody Begin device authorisation
	//
	// Opens an RFC 8628 device authorisation. Returns a user code for the human to type on the hub's verification page and a device code for the client to poll with. Nothing is authorised until a human approves that user code, so the response is not a credential grant — it is a pending request.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/device/authorize (the `DeviceAuthorize` operationId).
	DeviceAuthorizeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeviceAuthorize Begin device authorisation
	//
	// Opens an RFC 8628 device authorisation. Returns a user code for the human to type on the hub's verification page and a device code for the client to poll with. Nothing is authorised until a human approves that user code, so the response is not a credential grant — it is a pending request.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/device/authorize (the `DeviceAuthorize` operationId).
	DeviceAuthorize(ctx context.Context, body DeviceAuthorizeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeviceTokenWithBody Poll for the issued token
	//
	// Standard RFC 8628 polling. A code that has expired, been consumed, or been approved by an identity other than the requester is refused and no token is issued (FR-042). The issued token is a session for the identity that APPROVED the authorisation, so the machine holds exactly that person's access, re-derived from their groups on every request (FR-040, FR-044).
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/device/token (the `DeviceToken` operationId).
	DeviceTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeviceTokenWithFormdataBody Poll for the issued token
	//
	// Standard RFC 8628 polling. A code that has expired, been consumed, or been approved by an identity other than the requester is refused and no token is issued (FR-042). The issued token is a session for the identity that APPROVED the authorisation, so the machine holds exactly that person's access, re-derived from their groups on every request (FR-040, FR-044).
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type.
	//
	// Corresponds with POST /v1/device/token (the `DeviceToken` operationId).
	DeviceTokenWithFormdataBody(ctx context.Context, body DeviceTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Health Liveness and readiness
	//
	// Liveness and readiness in one probe: 200 when every dependency this role needs is reachable, 503 otherwise. Has no authenticated variant and no client error case (FR-058).
	//
	// Corresponds with GET /v1/health (the `Health` operationId).
	Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListProfiles Profiles readable by this identity
	//
	// Returns exactly the profiles this identity may read via direct membership or group mapping, and no others (FR-044). Not a filtered view of a larger list — unreadable profiles are not enumerated at all.
	//
	// Corresponds with GET /v1/profiles (the `ListProfiles` operationId).
	ListProfiles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRevision Fetch a resolved revision lockfile
	//
	// `revision` accepts `head` or an integer. The response body conforms to lockfile.schema.json, including the `skipped` array — a gate-excluded package is reported with its reason, never silently omitted (FR-036).
	//
	// Corresponds with GET /v1/profiles/{slug}/revisions/{revision} (the `GetRevision` operationId).
	GetRevision(ctx context.Context, slug string, revision string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReportSyncWithBody Report a completed sync
	//
	// Writes one sync_event and one audit row of kind `sync` (FR-050, R8). One call per sync, not per package — install counts are aggregated server-side from the revision's contents.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/sync (the `ReportSync` operationId).
	ReportSyncWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReportSync Report a completed sync
	//
	// Writes one sync_event and one audit row of kind `sync` (FR-050, R8). One call per sync, not per package — install counts are aggregated server-side from the revision's contents.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/sync (the `ReportSync` operationId).
	ReportSync(ctx context.Context, body ReportSyncJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetBundle Download an immutable version bundle
//
// Returns the `bundle.tar.zst` bytes, or a 307 to a pre-signed object-store URL. The `Digest` header carries the sha256 the client MUST verify before writing anything to disk. A rejected version is never served regardless of gate (FR-029).
//
// Corresponds with GET /v1/bundles/{publisher}/{name}/{version} (the `GetBundle` operationId).
func (c *Client) GetBundle(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBundleRequest(c.Server, publisher, name, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeviceAuthorizeWithBody Begin device authorisation
//
// Opens an RFC 8628 device authorisation. Returns a user code for the human to type on the hub's verification page and a device code for the client to poll with. Nothing is authorised until a human approves that user code, so the response is not a credential grant — it is a pending request.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/device/authorize (the `DeviceAuthorize` operationId).
func (c *Client) DeviceAuthorizeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeviceAuthorizeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeviceAuthorize Begin device authorisation
//
// Opens an RFC 8628 device authorisation. Returns a user code for the human to type on the hub's verification page and a device code for the client to poll with. Nothing is authorised until a human approves that user code, so the response is not a credential grant — it is a pending request.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/device/authorize (the `DeviceAuthorize` operationId).
func (c *Client) DeviceAuthorize(ctx context.Context, body DeviceAuthorizeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeviceAuthorizeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeviceTokenWithBody Poll for the issued token
//
// Standard RFC 8628 polling. A code that has expired, been consumed, or been approved by an identity other than the requester is refused and no token is issued (FR-042). The issued token is a session for the identity that APPROVED the authorisation, so the machine holds exactly that person's access, re-derived from their groups on every request (FR-040, FR-044).
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/device/token (the `DeviceToken` operationId).
func (c *Client) DeviceTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeviceTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeviceTokenWithFormdataBody Poll for the issued token
//
// Standard RFC 8628 polling. A code that has expired, been consumed, or been approved by an identity other than the requester is refused and no token is issued (FR-042). The issued token is a session for the identity that APPROVED the authorisation, so the machine holds exactly that person's access, re-derived from their groups on every request (FR-040, FR-044).
//
// Takes a body of the `application/x-www-form-urlencoded` content type.
//
// Corresponds with POST /v1/device/token (the `DeviceToken` operationId).
func (c *Client) DeviceTokenWithFormdataBody(ctx context.Context, body DeviceTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeviceTokenRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Health Liveness and readiness
//
// Liveness and readiness in one probe: 200 when every dependency this role needs is reachable, 503 otherwise. Has no authenticated variant and no client error case (FR-058).
//
// Corresponds with GET /v1/health (the `Health` operationId).
func (c *Client) Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListProfiles Profiles readable by this identity
//
// Returns exactly the profiles this identity may read via direct membership or group mapping, and no others (FR-044). Not a filtered view of a larger list — unreadable profiles are not enumerated at all.
//
// Corresponds with GET /v1/profiles (the `ListProfiles` operationId).
func (c *Client) ListProfiles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListProfilesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetRevision Fetch a resolved revision lockfile
//
// `revision` accepts `head` or an integer. The response body conforms to lockfile.schema.json, including the `skipped` array — a gate-excluded package is reported with its reason, never silently omitted (FR-036).
//
// Corresponds with GET /v1/profiles/{slug}/revisions/{revision} (the `GetRevision` operationId).
func (c *Client) GetRevision(ctx context.Context, slug string, revision string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRevisionRequest(c.Server, slug, revision)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReportSyncWithBody Report a completed sync
//
// Writes one sync_event and one audit row of kind `sync` (FR-050, R8). One call per sync, not per package — install counts are aggregated server-side from the revision's contents.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/sync (the `ReportSync` operationId).
func (c *Client) ReportSyncWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReportSyncRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReportSync Report a completed sync
//
// Writes one sync_event and one audit row of kind `sync` (FR-050, R8). One call per sync, not per package — install counts are aggregated server-side from the revision's contents.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/sync (the `ReportSync` operationId).
func (c *Client) ReportSync(ctx context.Context, body ReportSyncJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReportSyncRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBundleRequest constructs an http.Request for the GetBundle method
func NewGetBundleRequest(server string, publisher string, name string, version string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "publisher", publisher, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "version", version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/bundles/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeviceAuthorizeRequest calls the generic DeviceAuthorize builder with application/json body
func NewDeviceAuthorizeRequest(server string, body DeviceAuthorizeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeviceAuthorizeRequestWithBody(server, "application/json", bodyReader)
}

// NewDeviceAuthorizeRequestWithBody constructs an http.Request for the DeviceAuthorize method, with any body, and a specified content type
func NewDeviceAuthorizeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/device/authorize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeviceTokenRequestWithFormdataBody calls the generic DeviceToken builder with application/x-www-form-urlencoded body
func NewDeviceTokenRequestWithFormdataBody(server string, body DeviceTokenFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewDeviceTokenRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewDeviceTokenRequestWithBody constructs an http.Request for the DeviceToken method, with any body, and a specified content type
func NewDeviceTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/device/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthRequest constructs an http.Request for the Health method
func NewHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListProfilesRequest constructs an http.Request for the ListProfiles method
func NewListProfilesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/profiles")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRevisionRequest constructs an http.Request for the GetRevision method
func NewGetRevisionRequest(server string, slug string, revision string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "slug", slug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "revision", revision, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/profiles/%s/revisions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReportSyncRequest calls the generic ReportSync builder with application/json body
func NewReportSyncRequest(server string, body ReportSyncJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReportSyncRequestWithBody(server, "application/json", bodyReader)
}

// NewReportSyncRequestWithBody constructs an http.Request for the ReportSync method, with any body, and a specified content type
func NewReportSyncRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/sync")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetBundleWithResponse Download an immutable version bundle
	//
	// Returns the `bundle.tar.zst` bytes, or a 307 to a pre-signed object-store URL. The `Digest` header carries the sha256 the client MUST verify before writing anything to disk. A rejected version is never served regardless of gate (FR-029).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/bundles/{publisher}/{name}/{version} (the `GetBundle` operationId).
	GetBundleWithResponse(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*GetBundleResponse, error)

	// DeviceAuthorizeWithBodyWithResponse Begin device authorisation
	//
	// Opens an RFC 8628 device authorisation. Returns a user code for the human to type on the hub's verification page and a device code for the client to poll with. Nothing is authorised until a human approves that user code, so the response is not a credential grant — it is a pending request.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/device/authorize (the `DeviceAuthorize` operationId).
	DeviceAuthorizeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeviceAuthorizeResponse, error)

	// DeviceAuthorizeWithResponse Begin device authorisation
	//
	// Opens an RFC 8628 device authorisation. Returns a user code for the human to type on the hub's verification page and a device code for the client to poll with. Nothing is authorised until a human approves that user code, so the response is not a credential grant — it is a pending request.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/device/authorize (the `DeviceAuthorize` operationId).
	DeviceAuthorizeWithResponse(ctx context.Context, body DeviceAuthorizeJSONRequestBody, reqEditors ...RequestEditorFn) (*DeviceAuthorizeResponse, error)

	// DeviceTokenWithBodyWithResponse Poll for the issued token
	//
	// Standard RFC 8628 polling. A code that has expired, been consumed, or been approved by an identity other than the requester is refused and no token is issued (FR-042). The issued token is a session for the identity that APPROVED the authorisation, so the machine holds exactly that person's access, re-derived from their groups on every request (FR-040, FR-044).
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/device/token (the `DeviceToken` operationId).
	DeviceTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeviceTokenResponse, error)

	// DeviceTokenWithFormdataBodyWithResponse Poll for the issued token
	//
	// Standard RFC 8628 polling. A code that has expired, been consumed, or been approved by an identity other than the requester is refused and no token is issued (FR-042). The issued token is a session for the identity that APPROVED the authorisation, so the machine holds exactly that person's access, re-derived from their groups on every request (FR-040, FR-044).
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/device/token (the `DeviceToken` operationId).
	DeviceTokenWithFormdataBodyWithResponse(ctx context.Context, body DeviceTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*DeviceTokenResponse, error)

	// HealthWithResponse Liveness and readiness
	//
	// Liveness and readiness in one probe: 200 when every dependency this role needs is reachable, 503 otherwise. Has no authenticated variant and no client error case (FR-058).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/health (the `Health` operationId).
	HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResponse, error)

	// ListProfilesWithResponse Profiles readable by this identity
	//
	// Returns exactly the profiles this identity may read via direct membership or group mapping, and no others (FR-044). Not a filtered view of a larger list — unreadable profiles are not enumerated at all.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/profiles (the `ListProfiles` operationId).
	ListProfilesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListProfilesResponse, error)

	// GetRevisionWithResponse Fetch a resolved revision lockfile
	//
	// `revision` accepts `head` or an integer. The response body conforms to lockfile.schema.json, including the `skipped` array — a gate-excluded package is reported with its reason, never silently omitted (FR-036).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/profiles/{slug}/revisions/{revision} (the `GetRevision` operationId).
	GetRevisionWithResponse(ctx context.Context, slug string, revision string, reqEditors ...RequestEditorFn) (*GetRevisionResponse, error)

	// ReportSyncWithBodyWithResponse Report a completed sync
	//
	// Writes one sync_event and one audit row of kind `sync` (FR-050, R8). One call per sync, not per package — install counts are aggregated server-side from the revision's contents.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/sync (the `ReportSync` operationId).
	ReportSyncWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReportSyncResponse, error)

	// ReportSyncWithResponse Report a completed sync
	//
	// Writes one sync_event and one audit row of kind `sync` (FR-050, R8). One call per sync, not per package — install counts are aggregated server-side from the revision's contents.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/sync (the `ReportSync` operationId).
	ReportSyncWithResponse(ctx context.Context, body ReportSyncJSONRequestBody, reqEditors ...RequestEditorFn) (*ReportSyncResponse, error)
}

// GetBundleResponse200Headers the declared response headers of an HTTP 200 response for GetBundle
type GetBundleResponse200Headers struct {
	Digest *string
	ETag   *string
}

type GetBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Error
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetBundleResponse200Headers
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetBundleResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r GetBundleResponse) GetApplicationproblemJSON403() *Error {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetBundleResponse) GetApplicationproblemJSON404() *Error {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetBundleResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r GetBundleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBundleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DeviceAuthorizeResponse429Headers the declared response headers of an HTTP 429 response for DeviceAuthorize
type DeviceAuthorizeResponse429Headers struct {
	RetryAfter *int
}

type DeviceAuthorizeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DeviceAuthorization
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *Error
	// ApplicationproblemJSON415 the response for an HTTP 415 `application/problem+json` response
	ApplicationproblemJSON415 *Error
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
	// Headers429 the parsed response headers for an HTTP 429 response
	Headers429 *DeviceAuthorizeResponse429Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeviceAuthorizeResponse) GetJSON200() *DeviceAuthorization {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r DeviceAuthorizeResponse) GetApplicationproblemJSON400() *Error {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON415 returns the response for an HTTP 415 `application/problem+json` response
func (r DeviceAuthorizeResponse) GetApplicationproblemJSON415() *Error {
	return r.ApplicationproblemJSON415
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r DeviceAuthorizeResponse) GetApplicationproblemJSON422() *Error {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r DeviceAuthorizeResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r DeviceAuthorizeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeviceAuthorizeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeviceAuthorizeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeviceAuthorizeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeviceTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DeviceToken
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *DeviceTokenError
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeviceTokenResponse) GetJSON200() *DeviceToken {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeviceTokenResponse) GetJSON400() *DeviceTokenError {
	return r.JSON400
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r DeviceTokenResponse) GetApplicationproblemJSON400() *Error {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r DeviceTokenResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r DeviceTokenResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeviceTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeviceTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeviceTokenResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Health
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r HealthResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r HealthResponse) GetJSON503() *Health {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r HealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListProfilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ProfileList
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListProfilesResponse) GetJSON200() *ProfileList {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ListProfilesResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r ListProfilesResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r ListProfilesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListProfilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListProfilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListProfilesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetRevisionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Lockfile
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *Error
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetRevisionResponse) GetJSON200() *Lockfile {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetRevisionResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetRevisionResponse) GetApplicationproblemJSON404() *Error {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r GetRevisionResponse) GetApplicationproblemJSON422() *Error {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetRevisionResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r GetRevisionResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetRevisionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRevisionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRevisionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReportSyncResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *Error
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ReportSyncResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r ReportSyncResponse) GetApplicationproblemJSON404() *Error {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r ReportSyncResponse) GetApplicationproblemJSON422() *Error {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r ReportSyncResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r ReportSyncResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ReportSyncResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReportSyncResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReportSyncResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBundleWithResponse Download an immutable version bundle
//
// Returns the `bundle.tar.zst` bytes, or a 307 to a pre-signed object-store URL. The `Digest` header carries the sha256 the client MUST verify before writing anything to disk. A rejected version is never served regardless of gate (FR-029).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/bundles/{publisher}/{name}/{version} (the `GetBundle` operationId).
func (c *ClientWithResponses) GetBundleWithResponse(ctx context.Context, publisher string, name string, version string, reqEditors ...RequestEditorFn) (*GetBundleResponse, error) {
	rsp, err := c.GetBundle(ctx, publisher, name, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBundleResponse(rsp)
}

// DeviceAuthorizeWithBodyWithResponse Begin device authorisation
//
// Opens an RFC 8628 device authorisation. Returns a user code for the human to type on the hub's verification page and a device code for the client to poll with. Nothing is authorised until a human approves that user code, so the response is not a credential grant — it is a pending request.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/device/authorize (the `DeviceAuthorize` operationId).
func (c *ClientWithResponses) DeviceAuthorizeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeviceAuthorizeResponse, error) {
	rsp, err := c.DeviceAuthorizeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeviceAuthorizeResponse(rsp)
}

// DeviceAuthorizeWithResponse Begin device authorisation
//
// Opens an RFC 8628 device authorisation. Returns a user code for the human to type on the hub's verification page and a device code for the client to poll with. Nothing is authorised until a human approves that user code, so the response is not a credential grant — it is a pending request.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/device/authorize (the `DeviceAuthorize` operationId).
func (c *ClientWithResponses) DeviceAuthorizeWithResponse(ctx context.Context, body DeviceAuthorizeJSONRequestBody, reqEditors ...RequestEditorFn) (*DeviceAuthorizeResponse, error) {
	rsp, err := c.DeviceAuthorize(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeviceAuthorizeResponse(rsp)
}

// DeviceTokenWithBodyWithResponse Poll for the issued token
//
// Standard RFC 8628 polling. A code that has expired, been consumed, or been approved by an identity other than the requester is refused and no token is issued (FR-042). The issued token is a session for the identity that APPROVED the authorisation, so the machine holds exactly that person's access, re-derived from their groups on every request (FR-040, FR-044).
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/device/token (the `DeviceToken` operationId).
func (c *ClientWithResponses) DeviceTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeviceTokenResponse, error) {
	rsp, err := c.DeviceTokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeviceTokenResponse(rsp)
}

// DeviceTokenWithFormdataBodyWithResponse Poll for the issued token
//
// Standard RFC 8628 polling. A code that has expired, been consumed, or been approved by an identity other than the requester is refused and no token is issued (FR-042). The issued token is a session for the identity that APPROVED the authorisation, so the machine holds exactly that person's access, re-derived from their groups on every request (FR-040, FR-044).
//
// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/device/token (the `DeviceToken` operationId).
func (c *ClientWithResponses) DeviceTokenWithFormdataBodyWithResponse(ctx context.Context, body DeviceTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*DeviceTokenResponse, error) {
	rsp, err := c.DeviceTokenWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeviceTokenResponse(rsp)
}

// HealthWithResponse Liveness and readiness
//
// Liveness and readiness in one probe: 200 when every dependency this role needs is reachable, 503 otherwise. Has no authenticated variant and no client error case (FR-058).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/health (the `Health` operationId).
func (c *ClientWithResponses) HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResponse, error) {
	rsp, err := c.Health(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthResponse(rsp)
}

// ListProfilesWithResponse Profiles readable by this identity
//
// Returns exactly the profiles this identity may read via direct membership or group mapping, and no others (FR-044). Not a filtered view of a larger list — unreadable profiles are not enumerated at all.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/profiles (the `ListProfiles` operationId).
func (c *ClientWithResponses) ListProfilesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListProfilesResponse, error) {
	rsp, err := c.ListProfiles(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListProfilesResponse(rsp)
}

// GetRevisionWithResponse Fetch a resolved revision lockfile
//
// `revision` accepts `head` or an integer. The response body conforms to lockfile.schema.json, including the `skipped` array — a gate-excluded package is reported with its reason, never silently omitted (FR-036).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/profiles/{slug}/revisions/{revision} (the `GetRevision` operationId).
func (c *ClientWithResponses) GetRevisionWithResponse(ctx context.Context, slug string, revision string, reqEditors ...RequestEditorFn) (*GetRevisionResponse, error) {
	rsp, err := c.GetRevision(ctx, slug, revision, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRevisionResponse(rsp)
}

// ReportSyncWithBodyWithResponse Report a completed sync
//
// Writes one sync_event and one audit row of kind `sync` (FR-050, R8). One call per sync, not per package — install counts are aggregated server-side from the revision's contents.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/sync (the `ReportSync` operationId).
func (c *ClientWithResponses) ReportSyncWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReportSyncResponse, error) {
	rsp, err := c.ReportSyncWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReportSyncResponse(rsp)
}

// ReportSyncWithResponse Report a completed sync
//
// Writes one sync_event and one audit row of kind `sync` (FR-050, R8). One call per sync, not per package — install counts are aggregated server-side from the revision's contents.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/sync (the `ReportSync` operationId).
func (c *ClientWithResponses) ReportSyncWithResponse(ctx context.Context, body ReportSyncJSONRequestBody, reqEditors ...RequestEditorFn) (*ReportSyncResponse, error) {
	rsp, err := c.ReportSync(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReportSyncResponse(rsp)
}

// ParseGetBundleResponse parses an HTTP response from a GetBundleWithResponse call
func ParseGetBundleResponse(rsp *http.Response) (*GetBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 307:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetBundleResponse200Headers
		if values := rsp.Header.Values("Digest"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Digest", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Digest = &value
		}
		if values := rsp.Header.Values("ETag"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "ETag", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ETag = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseDeviceAuthorizeResponse parses an HTTP response from a DeviceAuthorizeWithResponse call
func ParseDeviceAuthorizeResponse(rsp *http.Response) (*DeviceAuthorizeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeviceAuthorizeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeviceAuthorization
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case rsp.StatusCode == 429:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 429:
		var headers DeviceAuthorizeResponse429Headers
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		response.Headers429 = &headers
	}

	return response, nil
}

// ParseDeviceTokenResponse parses an HTTP response from a DeviceTokenWithResponse call
func ParseDeviceTokenResponse(rsp *http.Response) (*DeviceTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeviceTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeviceToken
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.Header.Get("Content-Type") == "application/json" && rsp.StatusCode == 400:
		var dest DeviceTokenError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case rsp.Header.Get("Content-Type") == "application/problem+json" && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseHealthResponse parses an HTTP response from a HealthWithResponse call
func ParseHealthResponse(rsp *http.Response) (*HealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListProfilesResponse parses an HTTP response from a ListProfilesWithResponse call
func ParseListProfilesResponse(rsp *http.Response) (*ListProfilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListProfilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProfileList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetRevisionResponse parses an HTTP response from a GetRevisionWithResponse call
func ParseGetRevisionResponse(rsp *http.Response) (*GetRevisionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRevisionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Lockfile
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseReportSyncResponse parses an HTTP response from a ReportSyncWithResponse call
func ParseReportSyncResponse(rsp *http.Response) (*ReportSyncResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReportSyncResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}
