// These tests carry no `integration` tag on purpose. internal/store/schema holds
// two files that are copies of something the Go code already knows —
// 01-enums.sql restates models.EnumTypes() and 02-tables.sql is generated from
// the Bun models — and a copy that nothing compares is a copy that goes stale.
//
// The integration suite in store_test.go checks the same facts against a real
// migrated database, but that suite needs a container and CI runs only
// `go test ./...`. These two guards are the ones that fail a pull request.
package store_test

import (
	"os"
	"reflect"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"

	"agent-manager/internal/store/models"
)

func TestEnumSQLIsTheGoConstSets(t *testing.T) {
	b, err := os.ReadFile("schema/01-enums.sql")
	require.NoError(t, err)

	var got []string
	for _, line := range strings.Split(string(b), "\n") {
		if line = strings.TrimSpace(line); strings.HasPrefix(line, "create type") {
			got = append(got, line)
		}
	}

	require.Equal(t, models.EnumDDL(), got,
		"internal/store/schema/01-enums.sql is a hand-maintained copy of models.EnumDDL(); run it through EnumDDL again after changing an enum")
}

// TestGeneratedTableSQLMatchesTheModels is the container-free half of the
// staleness guard. 02-tables.sql is generated by `task migrate:schema`, but it is
// committed, so a new field on a Bun struct reaches the migration directory only
// if somebody remembered to regenerate. This fails when they did not.
func TestGeneratedTableSQLMatchesTheModels(t *testing.T) {
	b, err := os.ReadFile("schema/02-tables.sql")
	require.NoError(t, err)

	generated := parseGeneratedTables(t, string(b))

	db := bun.NewDB(nil, pgdialect.New())
	db.RegisterModel(models.All()...)
	tables := db.Dialect().Tables()

	wanted := map[string]bool{}
	for _, model := range models.All() {
		table := tables.Get(reflect.TypeOf(model).Elem())
		require.NotNil(t, table, "bun does not know model %T", model)
		wanted[table.Name] = true

		t.Run(table.Name, func(t *testing.T) {
			require.Contains(t, generated, table.Name,
				"table is registered in models.All() but absent from the generated SQL — run 'task migrate:schema'")
			for _, field := range table.Fields {
				require.Contains(t, generated[table.Name], field.Name,
					"column %s.%s exists on the Bun model but not in the generated SQL — run 'task migrate:schema'",
					table.Name, field.Name)
			}
		})
	}

	for table := range generated {
		require.True(t, wanted[table],
			"the generated SQL creates table %q, which no model in models.All() claims — run 'task migrate:schema'", table)
	}
}

var (
	createTableRE = regexp.MustCompile(`^CREATE TABLE "([^"]+)" \((.*)\);$`)
	columnRE      = regexp.MustCompile(`"([^"]+)" `)
)

// parseGeneratedTables reads table -> column set out of the loader's one-line-per
// -statement output. It is deliberately strict: an unrecognised line fails rather
// than being skipped, because a silently ignored CREATE TABLE would make the
// coverage assertion vacuous.
func parseGeneratedTables(t *testing.T, sql string) map[string]map[string]bool {
	t.Helper()

	out := map[string]map[string]bool{}
	for _, line := range strings.Split(sql, "\n") {
		line = strings.TrimSpace(line)
		switch {
		case line == "", strings.HasPrefix(line, "--"), strings.HasPrefix(line, "ALTER TABLE "):
			continue
		}

		m := createTableRE.FindStringSubmatch(line)
		require.NotNil(t, m, "unrecognised line in the generated SQL: %s", line)

		body := m[2]
		// Trim the trailing constraint clauses so PRIMARY KEY ("id") and
		// UNIQUE ("slug") do not read as columns.
		i := strings.Index(body, ", PRIMARY KEY (")
		require.GreaterOrEqual(t, i, 0, "every generated table must declare a primary key: %s", line)
		body = body[:i]

		columns := map[string]bool{}
		for _, c := range columnRE.FindAllStringSubmatch(body, -1) {
			columns[c[1]] = true
		}
		require.NotEmpty(t, columns, "no columns parsed out of: %s", line)
		out[m[1]] = columns
	}
	return out
}
