// These tests carry no `integration` tag on purpose. internal/store/schema holds
// two files that are copies of something the Go code already knows —
// 01-enums.sql restates models.EnumTypes() and 02-tables.sql is generated from
// the Bun models — and a copy that nothing compares is a copy that goes stale.
// specs/001-agent-manager-hub/data-model.md is a third copy, of the foreign-key
// set, and it goes stale the same way.
//
// The integration suite in store_test.go checks the same facts against a real
// migrated database, but that suite needs a container and CI runs only
// `go test ./...`. These guards are the ones that fail a pull request.
package store_test

import (
	"fmt"
	"os"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"

	"agent-manager/internal/store/models"
)

func TestEnumSQLIsTheGoConstSets(t *testing.T) {
	b, err := os.ReadFile("schema/01-enums.sql")
	require.NoError(t, err)

	var got []string
	for _, line := range strings.Split(string(b), "\n") {
		if line = strings.TrimSpace(line); strings.HasPrefix(line, "create type") {
			got = append(got, line)
		}
	}

	require.Equal(t, models.EnumDDL(), got,
		"internal/store/schema/01-enums.sql is a hand-maintained copy of models.EnumDDL(); run it through EnumDDL again after changing an enum")
}

// TestGeneratedTableSQLMatchesTheModels is the container-free half of the
// staleness guard. 02-tables.sql is generated by `task migrate:schema`, but it is
// committed, so a new field on a Bun struct reaches the migration directory only
// if somebody remembered to regenerate. This fails when they did not.
//
// BLIND SPOT, worth knowing here rather than in a design doc: this test — and
// `task gen:check`, which regenerates 02-tables.sql and diffs it — can only see a
// disagreement between the models and the loader's OUTPUT. Neither can see a
// foreign key the loader never emits. Eleven of the twenty-seven live in
// 03-constraints.sql by hand, and a model change lands in that eleven every time
// the foreign-key column is part of the primary key, which is the shape
// data-model.md mandates for signature and override. Comparing generated output
// against regenerated output is silent about all of it.
// TestDataModelDeclaresTheSameForeignKeys is the guard that actually covers it.
func TestGeneratedTableSQLMatchesTheModels(t *testing.T) {
	b, err := os.ReadFile("schema/02-tables.sql")
	require.NoError(t, err)

	generated := parseGeneratedTables(t, string(b))

	db := bun.NewDB(nil, pgdialect.New())
	db.RegisterModel(models.All()...)
	tables := db.Dialect().Tables()

	wanted := map[string]bool{}
	for _, model := range models.All() {
		table := tables.Get(reflect.TypeOf(model).Elem())
		require.NotNil(t, table, "bun does not know model %T", model)
		wanted[table.Name] = true

		t.Run(table.Name, func(t *testing.T) {
			require.Contains(t, generated, table.Name,
				"table is registered in models.All() but absent from the generated SQL — run 'task migrate:schema'")
			for _, field := range table.Fields {
				require.Contains(t, generated[table.Name], field.Name,
					"column %s.%s exists on the Bun model but not in the generated SQL — run 'task migrate:schema'",
					table.Name, field.Name)
			}
		})
	}

	for table := range generated {
		require.True(t, wanted[table],
			"the generated SQL creates table %q, which no model in models.All() claims — run 'task migrate:schema'", table)
	}
}

var (
	createTableRE = regexp.MustCompile(`^CREATE TABLE "([^"]+)" \((.*)\);$`)
	columnRE      = regexp.MustCompile(`"([^"]+)" `)
)

// parseGeneratedTables reads table -> column set out of the loader's one-line-per
// -statement output. It is deliberately strict: an unrecognised line fails rather
// than being skipped, because a silently ignored CREATE TABLE would make the
// coverage assertion vacuous.
func parseGeneratedTables(t *testing.T, sql string) map[string]map[string]bool {
	t.Helper()

	out := map[string]map[string]bool{}
	for _, line := range strings.Split(sql, "\n") {
		line = strings.TrimSpace(line)
		switch {
		case line == "", strings.HasPrefix(line, "--"), strings.HasPrefix(line, "ALTER TABLE "):
			continue
		}

		m := createTableRE.FindStringSubmatch(line)
		require.NotNil(t, m, "unrecognised line in the generated SQL: %s", line)

		body := m[2]
		// Trim the trailing constraint clauses so PRIMARY KEY ("id") and
		// UNIQUE ("slug") do not read as columns.
		i := strings.Index(body, ", PRIMARY KEY (")
		require.GreaterOrEqual(t, i, 0, "every generated table must declare a primary key: %s", line)
		body = body[:i]

		columns := map[string]bool{}
		for _, c := range columnRE.FindAllStringSubmatch(body, -1) {
			columns[c[1]] = true
		}
		require.NotEmpty(t, columns, "no columns parsed out of: %s", line)
		out[m[1]] = columns
	}
	return out
}

// ---------------------------------------------------------------------------
// design -> list -> database, guarded at the design end
// ---------------------------------------------------------------------------

// wantForeignKeys is the whole foreign-key set the schema is supposed to hold.
//
// IT MUST BE TRANSCRIBED BY HAND FROM internal/store/migrations, and never
// regenerated — not from data-model.md by the parser below, and not from the
// database by TestEveryForeignKeyIsPresent. A two-sided check is worth exactly
// the independence of its two sides: a list produced from either side turns the
// test on that side into a tautology, and the pair then agrees about anything.
//
// Twelve of these cannot come from the Bun models — ten because the base column
// is part of the primary key, which is a shape data-model.md mandates for
// signature and override; package.latest_version_id because a second belongs-to
// between package and version makes the Atlas loader's topological sort a cycle;
// and the composite package(publisher_id, namespace) key, which a bun tag has no
// way to spell at all. They are added by
// internal/store/schema/03-constraints.sql, so nothing in Go fails if a statement
// is lost from that file.
var wantForeignKeys = []string{
	// The twelve the loader cannot emit.
	"capability(version_id) -> version",
	"component(version_id) -> version",
	"membership(profile_id) -> profile",
	"override(finding_id) -> finding",
	"package(latest_version_id) -> version",
	// The composite key that holds package.namespace to its publisher's. It sits
	// beside the single-column package(publisher_id) key rather than replacing it:
	// the narrow one is what the bun belongs-to emits, and it is implied by this
	// one anyway.
	"package(publisher_id,namespace) -> publisher",
	"profile_entry(package_id) -> package",
	"profile_entry(profile_id) -> profile",
	"scan_check(scan_id) -> scan",
	"signature(version_id) -> version",
	"sync_target(profile_id) -> profile",
	"version_tag(version_id) -> version",
	// The seventeen the loader does emit, listed so an accidental loss on the
	// generated side fails here too.
	"device_authorization(approved_by_identity_id) -> identity",
	"finding(scan_id) -> scan",
	"finding(version_id) -> version",
	"finding_evidence(finding_id) -> finding",
	"override(reviewer_identity_id) -> identity",
	"package(category_id) -> category",
	"package(parent_package_id) -> package",
	"package(publisher_id) -> publisher",
	"profile(forked_from_id) -> profile",
	"profile_entry(pinned_version_id) -> version",
	"revision(profile_id) -> profile",
	"scan(version_id) -> version",
	"session(identity_id) -> identity",
	"sync_event(identity_id) -> identity",
	"sync_event(profile_id) -> profile",
	"sync_event(revision_id) -> revision",
	"version(package_id) -> package",
}

// `go test` runs with the package directory as the working directory, so this is
// the path relative to this file.
const dataModelPath = "../../specs/001-agent-manager-hub/data-model.md"

// TestDataModelDeclaresTheSameForeignKeys closes the transcription gap at the
// design end. TestEveryForeignKeyIsPresent proves the migrated database holds
// exactly wantForeignKeys; this proves data-model.md declares exactly the same
// set. Together they guard design -> list -> database at both links, and this
// link needs no container, so it is the one that fails a pull request.
func TestDataModelDeclaresTheSameForeignKeys(t *testing.T) {
	got := parseDesignForeignKeys(t, dataModelPath)

	// A parser that quietly matched nothing would make the comparison below pass
	// against an empty design, which is the failure mode a transcription check can
	// least afford. The floor is deliberately well under the real count: it fires
	// on a layout change that breaks extraction, and require.Equal pins the count.
	require.NotEmpty(t, got,
		"no foreign keys were extracted from %s at all — the table layouts have changed and this test is now vacuous", dataModelPath)
	require.GreaterOrEqual(t, len(got), 20,
		"only %d foreign keys were extracted from %s, which is too few to be a real reading of it", len(got), dataModelPath)

	want := append([]string(nil), wantForeignKeys...)
	sort.Strings(want)

	require.Equal(t, want, got,
		"data-model.md and wantForeignKeys disagree: either the design declares a foreign key the schema does not implement, or the schema grew one the design never asked for")
}

var (
	designTableRE  = regexp.MustCompile("^#{2,3}\\s+`([a-z_]+)`")
	designColumnRE = regexp.MustCompile("^`([a-z_]+)`\\s*(.*)$")
	designFKRE     = regexp.MustCompile(`\bfk\b`)
	// The optional parenthesised list is how a COMPOSITE foreign key is declared:
	// `fk (publisher_id, namespace) → publisher` on the second of its columns, and
	// nothing on the first, so it is emitted once and under the same column tuple
	// pg_constraint reports. Without it a two-column key could only be written as
	// two single-column ones, which is a different constraint.
	designTargetRE = regexp.MustCompile("\\bfk\\s*(?:\\(([a-z_, ]+)\\)\\s*)?→\\s*`?([a-z_]+)`?")
)

// parseDesignForeignKeys reads `table(column) -> target` out of data-model.md,
// whose tables come in two layouts: vertical, one column per row with the type in
// its own cell, and compact, every column of a narrow table on one row. The
// owning table is the nearest preceding backticked heading.
//
// There is deliberately NO inference of the target from the column name. The
// obvious heuristic — strip `_id` — reads override.reviewer_identity_id as
// pointing at `reviewer_identity`, a table that does not exist, when it points at
// `identity`; and it would read any future role-qualified column the same
// wrong-but-plausible way. So the design has to name the target and this fails
// when it does not.
func parseDesignForeignKeys(t *testing.T, path string) []string {
	t.Helper()

	b, err := os.ReadFile(path)
	require.NoError(t, err)

	var (
		out   []string
		table string
	)
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)

		if m := designTableRE.FindStringSubmatch(line); m != nil {
			table = m[1]
			continue
		}
		if !strings.HasPrefix(line, "|") {
			continue
		}

		cells := splitDesignRow(line)
		for i, cell := range cells {
			column, spec, ok := splitDesignCell(cell)
			if !ok {
				continue
			}
			// The vertical layout puts the type in the next cell; the compact layout
			// puts it in the same one. A next cell that names its own column is the
			// compact layout, and borrowing it would attribute a foreign key to the
			// column before it.
			if spec == "" && i+1 < len(cells) {
				if _, _, named := splitDesignCell(cells[i+1]); !named {
					spec = cells[i+1]
				}
			}
			if !designFKRE.MatchString(spec) {
				continue
			}
			require.NotEmpty(t, table, "a foreign key appears before any table heading: %s", line)

			m := designTargetRE.FindStringSubmatch(spec)
			require.NotNil(t, m,
				"%s.%s is declared `fk` without naming its target — write `fk → <table>`. "+
					"Guessing the target from the column name is what this test refuses to do: "+
					"stripping `_id` gets override.reviewer_identity_id wrong, and a plausible "+
					"wrong target is worse than a failure here", table, column)

			columns := column
			if m[1] != "" {
				columns = strings.Join(strings.Fields(strings.ReplaceAll(m[1], ",", " ")), ",")
			}
			out = append(out, fmt.Sprintf("%s(%s) -> %s", table, columns, m[2]))
		}
	}
	sort.Strings(out)

	return out
}

func splitDesignRow(line string) []string {
	cells := strings.Split(strings.Trim(line, "|"), "|")
	for i := range cells {
		cells[i] = strings.TrimSpace(cells[i])
	}
	return cells
}

// splitDesignCell reports whether the cell opens with a backticked column name,
// and returns the name and whatever follows it.
func splitDesignCell(cell string) (column, spec string, ok bool) {
	m := designColumnRE.FindStringSubmatch(cell)
	if m == nil {
		return "", "", false
	}
	return m[1], strings.TrimSpace(m[2]), true
}
